### ISSUE TITLE
Failure: plugin protoc-gen-prost-crate: could not find insertion point "features" in "Cargo.toml"

### ISSUE THREAD

**Issue by listepo** [neoeinstein/protoc-gen-prost#115]
buf.gen.yaml
```
version: v2
plugins:
  - local: protoc-gen-prost
    out: client_api/src/gen/grpc
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
      - enable_type_names
  - local: protoc-gen-prost-serde
    out: client_api/src/gen/grpc
  - local: protoc-gen-tonic
    out: client_api/src/gen/grpc
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
  - local: protoc-gen-prost-crate
    out: client_api
    opt:
      - include_file=src/gen/grpc/mod.rs
      - gen_crate=client_api/Cargo.toml
    strategy: all
```

Cargo.toml
```
[features]
postgres = []
reflection = ["dep:tonic-reflection"]
prisma = ["prisma-client-rust/postgresql"]
v1-auth = []
v1-account = []
v1-account_type = []
v1-category = []
v1-currency = []
v1-transaction = []
v1-transaction_type = []

```
