### ISSUE TITLE
Error Multi Inputs

### ISSUE THREAD

**Issue by cpeliciari** [neoeinstein/protoc-gen-prost#116]
Below is my buf.gen.yaml, but when I generate my code, my mod.rs is incomplete—it is only including one module.

mod.rs
```
// @generated
pub mod subscription {
    #[cfg(feature = "subscription_v1")]
    // @@protoc_insertion_point(attribute:subscription.v1)
    pub mod v1 {
        include!("subscription.v1.rs");
        // @@protoc_insertion_point(subscription.v1)
    }
}
```

buf.gen.yaml
``` 
version: v2
managed:
  enabled: true

plugins:
  - remote: buf.build/community/neoeinstein-prost:v0.4.0
    out: gen/src
    opt:
      - bytes=.
      - compile_well_known_types
      - file_descriptor_set
      - enable_type_names
  - remote: buf.build/community/neoeinstein-tonic:v0.4.1
    out: gen/src
    opt:
      - compile_well_known_types
  - local: protoc-gen-prost-crate
    strategy: all
    out: gen
    opt:
      - include_file=mod.rs
      - gen_crate=Cargo.toml
      - package_separator=_

inputs:
  - git_repo: ssh://github.com/org_1/publisher.git
    branch: main
    subdir: .
    depth: 3
  - git_repo: ssh://github.com/org_1/metrics.git
    branch: main
    subdir: .
    depth: 3
  - git_repo: ssh://github.com/org_1/subscription.git
    branch: main
    subdir: .
    depth: 3
```

**Comment by neoeinstein** [comment]
`protoc-gen-prost-crate` is not going to be compatible with multiple inputs from `buf.gen.yaml`. It requires having the _complete_ context (as evidenced by requiring `strategy: all`), but each input is sent through the generation pipeline independently. `-crate` is generating `mod.rs` for _each_ input, but the file is getting overwritten for each input, which is why you're observing `mod.rs` only containing reference to `subscription` — it's the last input to have overwritten `mod.rs`. This is not something that I can easily workaround, as `protoc` plugins don't have access to know whether a file already exists on the filesystem, and `protoc` takes the outputs and overwrites any existing files. Merging only works if the file is part of a context that was generated in a given `protoc` invocation, so I can't add to or manipulate files generated for prior inputs.

I'd recommend splitting this up into 3 distinct crates or modules to house the generated code for your inputs.

**Comment by cpeliciari** [comment]
Don’t you think it’s interesting to generate a different crate for each input based on the folder?

In Go, for example, it creates a package for each input.

![Image](https://github.com/user-attachments/assets/8f639dc8-b13b-4a60-9c2e-4fe0e60eb63c)


```
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: "github.com/org_1/lib/gen"

plugins:
  - remote: buf.build/grpc/go:v1.5.1
    out: gen
    opt:
      - paths=source_relative
  - remote: buf.build/protocolbuffers/go:v1.34.2
    out: gen
    opt: paths=source_relative

inputs:
  - git_repo: ssh://github.com/org_1/publisher.git
    branch: main
    subdir: .
    depth: 30
  - git_repo: ssh://github.com/org_1/metrics.git
    branch: main
    subdir: .
    depth: 30
  - git_repo: ssh://github.com/org_1/subscription.git
    branch: main
    subdir: .
    depth: 30

```
