### ISSUE TITLE
Issue with v2 of buf.build

### ISSUE THREAD

**Issue by davidyannick86** [neoeinstein/protoc-gen-prost#121]
I've tried a buf generate with your example and I've adapted both buf files as I do with GO successfully: 

buf.yaml:

```
version: v2

modules:
- path: proto

``` 

and buf.gen.yaml:

```
version: v2

plugins:

- remote: buf.build/community/neoeinstein-prost:v0.4.0
  out: src/gen
  opt:
  - compile_well_known_types
  - extern_path=.google.protobuf=::pbjson_types
  - file_descriptor_set
  - enable_type_names

- remote: buf.build/community/neoeinstein-prost-serde:v0.3.1
  out: src/gen

- remote: buf.build/community/neoeinstein-tonic:v0.4.1
  out: src/gen
  opt:
  - compile_well_known_types
  - extern_path=.google.protobuf=::pbjson_types

- remote: buf.build/community/neoeinstein-prost-crate:v0.4.1
  out: .
  strategy: all
  opt:
  - include_file=src/gen/mod.rs
  - gen_crate
```

But when I run buf generate with strategy I have an error : 

"Failure: decode buf.gen.yaml: cannot specify strategy for remote plugin buf.build/community/neoeinstein-prost-crate:v0.4.1"

And if I delete strategy : 

"Failure: failed_precondition: plugin "buf.build/community/neoeinstein-prost-crate:v0.4.1" failed: No such file or directory (os error 2)"

I've uploaded the files here if needed https://github.com/davidyannick86/build-with-buf

Can you help me please ?

thanks
