### ISSUE TITLE
crate:v0.1.5-2 failed no such file or directory

### ISSUE THREAD

**Issue by hexfusion** [neoeinstein/protoc-gen-prost#3]
The prost crate plugin is not working might need a new tag pushed? 

```
  - remote: buf.build/prost/plugins/crate:v0.1.5-2
    out: .
    opt:
      - include_file=src/gen/mod.rs
      - gen_crate
 ```

```
Failure: plugin "buf.build/prost/plugins/crate:v0.1.5-2" failed: No such file or directory (os error 2)
```
