### ISSUE TITLE
`protoc-gen-prost-serde` with external types?

### ISSUE THREAD

**Issue by stephanos** [neoeinstein/protoc-gen-prost#31]
I've been trying to use an external type in my proto file and it now finally works with `protoc-gen-prost-crate` but not `protoc-gen-prost-serde`.

The proto file:
```proto
import "google/rpc/status.proto";

message CommandResult {
    google.rpc.Status status = 1 ;
}
```

The buf.gen.yaml:
```yaml
version: v1

plugins:
  - remote: buf.build/prost/plugins/prost:v0.2.0-2
    out: target/gen
    opt:
      - bytes=.
      - extern_path=.google=::google_api_proto::google
  - remote: buf.build/prost/plugins/serde:v0.2.0-2
    out: target/gen
    opt:
      - no_include
      - extern_path=.google=::google_api_proto::google
```

I've added `google-api-proto = { version = "1.38.0", features = ["google-rpc"] }` to Cargo.toml to provide the external type.

The error:
```
error[E0277]: the trait bound `Status: Serialize` is not satisfied
     |
331  |             struct_ser.serialize_field("status", v)?;
     |                        ---------------           ^ the trait `Serialize` is not implemented for `Status`
```

It seems that `protoc-gen-prost-serde` does not generate anything for the external type `Status`.

Is there a solution?
