### ISSUE TITLE
reflection fails for compile_well_known_types

### ISSUE THREAD

**Issue by hexfusion** [neoeinstein/protoc-gen-prost#4]
```
  - name: prost
    out: src/gen
    opt:
      - bytes=.
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
 ```
 
 This works great and I have reflection setup but when I call it it fails.
 ```
 'google/protobuf/empty.proto' not found
 ```
 
 ```
 tonic_reflection::server::Builder::configure()
         .register_encoded_file_descriptor_set(proto::name::FILE_DESCRIPTOR_SET)
 ```
 
 It seems like pbjson-types should handle this and I see that it generates a bin file but I don't see a way to consume it. Am I missing something or is this a bug? Thanks
 
 ```
 build/pbjson-types-7ae7be497a9998f0/out/proto_descriptor.bin
 ```
