### ISSUE TITLE
Reflection Not Working With Google Protobufs

### ISSUE THREAD

**Issue by cobbinma** [neoeinstein/protoc-gen-prost#53]
Hey 👋

`tonic_reflection` seems broken when using the file descriptor sets generated when the api contains any google protobufs. 

Got this error when trying to use `grpcui`.

```sh
Failed to compute set of methods to expose: Symbol not found: reporting.api.v1.ReportingService
caused by: File not found: google/protobuf/empty.proto
```

```rust
    Server::builder()
        .add_service(
            tonic_reflection::server::Builder::configure()
                .register_encoded_file_descriptor_set(grpc::reporting::api::v1::FILE_DESCRIPTOR_SET)
                .build()?,
        )
```

```yaml
  - remote: buf.build/prost/plugins/prost:v0.2.1-1
    out: autogen/lang/rust
    opt:
      - bytes=.
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
  - remote: buf.build/prost/plugins/serde:v0.2.1-1
    out: autogen/lang/rust
  - remote: buf.build/prost/plugins/tonic:v0.2.1-1
    out: autogen/lang/rust
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
  - remote: buf.build/prost/plugins/crate:v0.3.1-1
    out: autogen/lang/rust
    opt:
      - no_features
```

```toml
tonic-reflection = "0.6.0"
```
