### ISSUE TITLE
plugin prost-crate: The system couldn't find the given file. (os error 2)

### ISSUE THREAD

**Issue by teamplayer3** [neoeinstein/protoc-gen-prost#56]
My directory structure:

```
- root
  - api-crate
    - src
    | Cargo.toml
  - proto
    | buf.yaml
  | buf.gen.yaml
  | buf.work.yaml 
```

`protoc-gen-prost-crate` version v0.3.1

Now I run `buf generate` in the root directory, and it exits with error: 

```
plugin prost-crate: The system couldn't find the given file. (os error 2)
```

buf.gen.yaml:

```yaml
version: v1
plugins:
  - remote: buf.build/prost/plugins/prost:v0.2.1-1
    out: api-crate/src/gen
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
  - remote: buf.build/prost/plugins/serde:v0.2.1-1
    out: api-crate/src/gen
  - remote: buf.build/prost/plugins/tonic:v0.2.1-1
    out: api-crate/src/gen
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
  - name: prost-crate
    out: api-crate
    strategy: all
    opt:
      - include_file=api-crate/src/gen/mod.rs
      - gen_crate
```
