### ISSUE TITLE
protoc-gen-prost-serde: doesn't generate .serde.rs for module with "type" in its name

### ISSUE THREAD

**Issue by gwik** [neoeinstein/protoc-gen-prost#57]
Hi,

protoc-gen-prost-serde doesn't generate `${package}.serde.rs` for packages with "type" in their name,
e.g: `envoy.type.v3.rs`, while it does for any other package.

```
version: v1
plugins:
  - remote: buf.build/prost/plugins/prost:v0.2.1-1
    out: gen
    opt:
      - bytes=.
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
  - remote: buf.build/prost/plugins/serde:v0.2.1-1
      out: gen
      opt:
        - extern_path=.google.protobuf=::pbjson_types
  - remote: buf.build/prost/plugins/tonic:v0.2.1-1
    out: gen
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
  - name: prost-crate
    out: .
    strategy: all
    opt:
      - gen_crate=Cargo.tpl.toml
      - include_file=gen/mod.rs
      - no_features
```
