### ISSUE TITLE
Failure when compiling with file_descriptor_set

### ISSUE THREAD

**Issue by gwik** [neoeinstein/protoc-gen-prost#59]
Hi,

I have a failure compiling some protos with buf:

```
version: v1
plugins:
  - plugin: prost
    out: gen
    opt:
      - bytes=.
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
```

```
Failure: plugin prost: envoy.service.auth.v2alpha.rs: does not exist
```

I'm using prost plugin compiled from main (44d3fc389cd05e4e8060fe296770677d1f066e16).

The failure happens because the prost code generation might omit empty files but the `file_descriptor_set` option makes it needed. Removing `file_descriptor_set` makes it work.

The problem starts with commit 038cd342677dfa869f8c3a2a2787a139fc561df8 when `prost-build` crate was upgraded.

I have a draft PR that fixes the issue, but I don't think it should be merged as is:

https://github.com/neoeinstein/protoc-gen-prost/pull/58/commits/34c2ac3610b6688caa68da886c4b0478893828df
