### ISSUE TITLE
Failure: plugin prost-crate: could not find protoc plugin for name prost-crate - please make sure protoc-gen-prost-crate is installed and present on your $PATH

### ISSUE THREAD

**Issue by listepo** [neoeinstein/protoc-gen-prost#81]
buf.gen.yaml

```yaml
version: v1
plugins:
  - plugin: prost
    out: gen/src
    opt:
      - bytes=.
      - file_descriptor_set
  - plugin: prost-serde
    out: gen/src
  - plugin: prost-crate
    out: gen
    strategy: all
    opt:
      - gen_crate=Cargo.toml.tpl
```

`buf generate`

Failure: plugin prost-crate: could not find protoc plugin for name prost-crate - please make sure protoc-gen-prost-crate is installed and present on your $PATH
