### ISSUE TITLE
Handle protobuf package name `_` in prost-crate

### ISSUE THREAD

**Issue by stefanvanburen** [neoeinstein/protoc-gen-prost#96]
Hi! This is an admittedly contrived example but figured I'd report anyway.

```proto
// File: test.proto
syntax = "proto3";

package _;

message Test {}
```

```yaml
# buf.gen.yaml
version: v1
plugins:
  - plugin: buf.build/community/neoeinstein-prost
    out: gen/src
  - plugin: buf.build/community/neoeinstein-prost-crate
    out: gen
    opt:
      - no_features
```

Run `buf generate .`. You'll end up with `gen/mod.rs`:

```
// @generated
// @@protoc_insertion_point(attribute:_)
pub mod  {
    include!("_.rs");
    // @@protoc_insertion_point(_)
}
```

The `mod` name is empty, which I _think_ is invalid based on my read of the [rust reference for modules](https://doc.rust-lang.org/reference/items/modules.html). It looks like it's avoiding making the module name `_`, which is similarly invalid, based on the [identifiers spec](https://doc.rust-lang.org/reference/identifiers.html) line:

> with the additional constraint that a single underscore character is not an identifier.

Not really sure what to do other than to error with a `_` package.

**Comment by stefanvanburen** [comment]
Actually, based on what Prost is doing with identifiers, maybe you could change the identifier to `__` (double underscore), which would be a valid identifier, at least?: https://github.com/tokio-rs/prost/blob/e3deaa200b3a5500bf0403325d02716973b7296a/prost-build/src/ident.rs#L23. However, `__` is a valid Protobuf package name too, so you'd potentially conflict with that package 😃.

**Comment by stefanvanburen** [comment]
Also:

```
// File: test1.proto
syntax = "proto3";

package _;

message Test {}
```

```
// File: test2.proto
syntax = "proto3";

message Test {}
```

```yaml
# buf.gen.yaml
version: v1
plugins:
  - plugin: buf.build/community/neoeinstein-prost
    out: gen/src
```

Generates two files, named `_` and `_.rs`, both containing:

```
// @generated
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Test {
}
// @@protoc_insertion_point(module)
```

Again, not sure the answer, but it doesn't seem like generating a file named `_` is desirable.
